services:
  - type: web
    name: matchbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT bot:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
    autoDeploy: true